---
tags: ["Bug","Error-Reporting","alignment","data-analysis","data-science","flexible","pandas","python"]
title: "BUG: df.mask with int df throws ValueError instead of TypeError"
html_url: "https://github.com/pandas-dev/pandas/issues/56330"
user: "sfc-gh-rdurrani"
repo: "pandas-dev/pandas"
---

